language: php

php:
  - 7.0
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - composer selfupdate
  - composer install --dev --prefer-dist

script:
  - ./vendor/bin/phpunit --coverage-clover clover.xml

after_success:
  - ./vendor/bin/test-reporter --coverage-report clover.xml